internal/app/zscaler-terraformer/cmd/generate_test.go
internal/app/zscaler-terraformer/cmd/import.go
internal/app/zscaler-terraformer/cmd/root.go
internal/app/zscaler-terraformer/cmd/util.go
internal/app/zscaler-terraformer/cmd/version.go

Fix: zia_url_filtering_rule not importing

Fix: zia_url_filtering_rule not importing

---

.github/workflows/test.yaml
Makefile
internal/app/zscaler-terraformer/cmd/generate.go
internal/app/zscaler-terraformer/cmd/import.go
internal/app/zscaler-terraformer/cmd/root.go
internal/app/zscaler-terraformer/cmd/version.go

Excluded O365 default network app group

Excluded O365 default network app group

---

.github/workflows/test.yaml
Makefile
internal/app/zscaler-terraformer/cmd/root.go
internal/app/zscaler-terraformer/cmd/version.go

fix version flag and zpa cloud types

fix version flag and zpa cloud types

---

internal/app/zscaler-terraformer/cmd/generate.go
internal/app/zscaler-terraformer/cmd/import.go
internal/app/zscaler-terraformer/cmd/root.go

Added ``--exclude`` flag to list of flags

Added ``--exclude`` flag to list of flags

---

internal/app/zscaler-terraformer/cmd/generate.go
internal/app/zscaler-terraformer/cmd/import.go
internal/app/zscaler-terraformer/cmd/root.go
internal/app/zscaler-terraformer/cmd/util.go
internal/app/zscaler-terraformer/cmd/version.go

Added ``--version`` flag

---

.gitignore
go.mod
go.sum
internal/app/zscaler-terraformer/cmd/generate.go

remove resource ID suffix when name is used

---

.gitignore
go.mod
go.sum
internal/app/zscaler-terraformer/cmd/util.go

fix float round to int

---

README.md
go.mod
go.sum
internal/app/zscaler-terraformer/cmd/import.go
testdata/zia/zia_admin_users.yaml
testdata/zia/zia_auth_settings_urls.yaml
testdata/zia/zia_dlp_dictionaries.yaml
testdata/zia/zia_dlp_notification_templates.yaml
testdata/zia/zia_dlp_web_rules.yaml
testdata/zia/zia_firewall_filtering_destination_groups.yaml
testdata/zia/zia_firewall_filtering_ip_source_groups.yaml
testdata/zia/zia_firewall_filtering_network_application_groups.yaml
testdata/zia/zia_firewall_filtering_network_service.yaml
testdata/zia/zia_firewall_filtering_network_service_groups.yaml
testdata/zia/zia_firewall_filtering_rule.yaml
testdata/zia/zia_location_management.yaml
testdata/zia/zia_rule_labels.yaml
testdata/zia/zia_security_settings.yaml
testdata/zia/zia_traffic_forwarding_gre_tunnel.yaml
testdata/zia/zia_traffic_forwarding_static_ip.yaml
testdata/zia/zia_traffic_forwarding_vpn_credentials.yaml
testdata/zia/zia_url_categories.yaml
testdata/zia/zia_url_filtering_rules.yaml
testdata/zia/zia_user_management.yaml

Fix) Added missed traffic_forwarding_gretunnel

Fix) Added missed traffic_forwarding_gretunnel

---

go.mod
go.sum
internal/app/zscaler-terraformer/cmd/generate.go

intall TF latest version only when it is not

---

.github/workflows/test.yaml
CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
internal/app/zscaler-terraformer/cmd/generate.go
internal/app/zscaler-terraformer/cmd/import.go

(fix): Fixed  to import sublocations

(fix): Fixed  to import sublocations

---

.github/workflows/test.yaml
CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
internal/app/zscaler-terraformer/cmd/generate.go
internal/app/zscaler-terraformer/cmd/generate_test.go
internal/app/zscaler-terraformer/cmd/import.go
internal/app/zscaler-terraformer/cmd/type.go
internal/app/zscaler-terraformer/cmd/util.go
testdata/terraform/zia/zia_admin_users/test.tf
testdata/terraform/zpa/zpa_application_segment_inspection/test.tf

Fix: Fixed Pointers to new SDK v2.2.2 structure

Fix: Fixed Pointers to new SDK v2.2.2 structure

---

.github/workflows/release.yaml
.github/workflows/test.yaml
CHANGELOG.md
docs/guides/release-notes.md
internal/app/zscaler-terraformer/cmd/generate.go
internal/app/zscaler-terraformer/cmd/generate_test.go
internal/app/zscaler-terraformer/cmd/import.go
internal/app/zscaler-terraformer/cmd/type.go
internal/app/zscaler-terraformer/cmd/util.go

feat: Added Import capability to new supported resources

feat: Added Import capability to new supported resources

---

CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
internal/app/zscaler-terraformer/cmd/generate.go
internal/app/zscaler-terraformer/cmd/util.go

Fix: Fixed ZIA Firewall Rule nested attribute ID format type

Fix: Fixed ZIA Firewall Rule nested attribute ID format type

---

CHANGELOG.md
docs/guides/release-notes.md
internal/app/zscaler-terraformer/cmd/generate.go
internal/app/zscaler-terraformer/cmd/import.go
internal/app/zscaler-terraformer/cmd/util.go

Fix: Fixed ZIA Nested Blocks ID conversion

Fix: Fixed ZIA Nested Blocks ID conversion

---

CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
internal/app/zscaler-terraformer/cmd/util.go

fix: Fixed zia_url_filtering_rules nested attributes

fix: Fixed zia_url_filtering_rules nested attributes

---

CHANGELOG.md
docs/guides/release-notes.md
internal/app/zscaler-terraformer/cmd/generate.go
internal/app/zscaler-terraformer/cmd/util.go

Fix: Fixed ZPA computed and nested attributes

Fix: Fixed ZPA computed and nested attributes

---

.gitignore
CHANGELOG.md
Makefile
docs/guides/release-notes.md
internal/app/zscaler-terraformer/cmd/version.go

fix: Improved version command output

fix: Improved version command output

---

CHANGELOG.md
README.md
docs/guides/release-notes.md
internal/app/zscaler-terraformer/cmd/generate.go
internal/app/zscaler-terraformer/cmd/generate_test.go
internal/app/zscaler-terraformer/cmd/import.go
internal/app/zscaler-terraformer/cmd/type.go
internal/app/zscaler-terraformer/cmd/util.go

fix: Temporary ZPA resource deprecation

fix: Temporary ZPA resource deprecation

---

CHANGELOG.md
cmd/generate.go
cmd/import.go
docs/guides/release-notes.md
go.mod
go.sum

Fix: Fixed Loop Conditions during Resource import zpa_inspection_custom_controls

Fix: Fixed Loop Conditions during Resource import zpa_inspection_custom_controls

---

.github/CODEOWNERS
.github/pull_request_template.md
CHANGELOG.md
cmd/import.go
docs/guides/release-notes.md

fix: Applied license error handling to all ZPA privileged remote access resources

fix: Applied license error handling to all ZPA privileged remote access resources

---

CHANGELOG.md
docs/guides/release-notes.md
terraformutils/nesting/nesting.go

fix: Fixed ZIA  edge case attributes

---

CHANGELOG.md
docs/guides/release-notes.md
terraformutils/helpers/helpers.go
terraformutils/nesting/nesting.go

fix: Fixed ZIA SSL Inspection attribute

---

CHANGELOG.md
cmd/generate.go
docs/guides/release-notes.md
docs/guides/support.md
terraformutils/nesting/nesting.go
terraformutils/version.go

fix: Fixed ZIA Destination Groups and DLP Dictionairies

---

CHANGELOG.md
docs/guides/release-notes.md
go.mod
go.sum
terraformutils/nesting/nesting.go

fix: Fixed url filtering rule cbi_profile edge case

---

CHANGELOG.md
docs/guides/release-notes.md
terraformutils/helpers/helpers.go
terraformutils/nesting/nesting.go

fix: Fixed zia_forwarding_control_zpa_gateway to handle zpa_app_segments

---

CHANGELOG.md
README.md
cmd/generate.go
cmd/import.go
cmd/root.go
docs/guides/release-notes.md
go.mod
go.sum
terraformutils/nesting/nesting.go
terraformutils/version.go

fix: Fixed DLP Web Rules Receiver attribute and End User Notification

---

CHANGELOG.md
cmd/generate.go
docs/guides/release-notes.md
terraformutils/nesting/nesting.go
terraformutils/version.go

fix: Excluded ZIA Url Category computed attribute
